"""add new_email_tmp

Revision ID: 030a264a50ae
Revises: 357df838f0ac
Create Date: 2017-09-18 23:41:35.747321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '030a264a50ae'
down_revision = '357df838f0ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('new_email_temp', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_new_email_temp'), 'users', ['new_email_temp'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_new_email_temp'), table_name='users')
    op.drop_column('users', 'new_email_temp')
    # ### end Alembic commands ###
