"""add new_password_temp

Revision ID: 357df838f0ac
Revises: 02bcf59a82c9
Create Date: 2017-09-18 01:29:50.913316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '357df838f0ac'
down_revision = '02bcf59a82c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('new_password_temp_hash', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'new_password_temp_hash')
    # ### end Alembic commands ###
